//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
///PPP added
using System.Globalization;

// 
// This source code was auto-generated by wsdl, Version=4.0.21006.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="LocationsSoap", Namespace="http://www.GEOvision.dk/MapToWeb/Locations")]
public partial class Locations : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getLocationOperationCompleted;
    
    private System.Threading.SendOrPostCallback getLocationWithInfoOperationCompleted;
    
    private System.Threading.SendOrPostCallback getLocationListOperationCompleted;
    
    /// <remarks/>
    public Locations() {
        this.Url = "http://www.maptoweb.dk/MapToWeb/Locations.asmx";
    }
    
    /// <remarks/>
    public event getLocationCompletedEventHandler getLocationCompleted;
    
    /// <remarks/>
    public event getLocationWithInfoCompletedEventHandler getLocationWithInfoCompleted;
    
    /// <remarks/>
    public event getLocationListCompletedEventHandler getLocationListCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.GEOvision.dk/MapToWeb/Locations/getLocation", RequestNamespace="http://www.GEOvision.dk/MapToWeb/Locations", ResponseNamespace="http://www.GEOvision.dk/MapToWeb/Locations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public LocationGeoInfo getLocation(Location objLocation, bool exactMatch, string MapToWebUser) {
        object[] results = this.Invoke("getLocation", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser});
        return ((LocationGeoInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLocation(Location objLocation, bool exactMatch, string MapToWebUser, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLocation", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser}, callback, asyncState);
    }
    
    /// <remarks/>
    public LocationGeoInfo EndgetLocation(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((LocationGeoInfo)(results[0]));
    }
    
    /// <remarks/>
    public void getLocationAsync(Location objLocation, bool exactMatch, string MapToWebUser) {
        this.getLocationAsync(objLocation, exactMatch, MapToWebUser, null);
    }
    
    /// <remarks/>
    public void getLocationAsync(Location objLocation, bool exactMatch, string MapToWebUser, object userState) {
        if ((this.getLocationOperationCompleted == null)) {
            this.getLocationOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLocationOperationCompleted);
        }
        this.InvokeAsync("getLocation", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser}, this.getLocationOperationCompleted, userState);
    }
    
    private void OngetLocationOperationCompleted(object arg) {
        if ((this.getLocationCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLocationCompleted(this, new getLocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.GEOvision.dk/MapToWeb/Locations/getLocationWithInfo", RequestNamespace="http://www.GEOvision.dk/MapToWeb/Locations", ResponseNamespace="http://www.GEOvision.dk/MapToWeb/Locations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocationInfo[] getLocationWithInfo(Location objLocation, bool exactMatch, string MapToWebUser) {
        object[] results = this.Invoke("getLocationWithInfo", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser});
        return ((LocationInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLocationWithInfo(Location objLocation, bool exactMatch, string MapToWebUser, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLocationWithInfo", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser}, callback, asyncState);
    }
    
    /// <remarks/>
    public LocationInfo[] EndgetLocationWithInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((LocationInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void getLocationWithInfoAsync(Location objLocation, bool exactMatch, string MapToWebUser) {
        this.getLocationWithInfoAsync(objLocation, exactMatch, MapToWebUser, null);
    }
    
    /// <remarks/>
    public void getLocationWithInfoAsync(Location objLocation, bool exactMatch, string MapToWebUser, object userState) {
        if ((this.getLocationWithInfoOperationCompleted == null)) {
            this.getLocationWithInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLocationWithInfoOperationCompleted);
        }
        this.InvokeAsync("getLocationWithInfo", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser}, this.getLocationWithInfoOperationCompleted, userState);
    }
    
    private void OngetLocationWithInfoOperationCompleted(object arg) {
        if ((this.getLocationWithInfoCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLocationWithInfoCompleted(this, new getLocationWithInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.GEOvision.dk/MapToWeb/Locations/getLocationList", RequestNamespace="http://www.GEOvision.dk/MapToWeb/Locations", ResponseNamespace="http://www.GEOvision.dk/MapToWeb/Locations", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
    public LocationGeoInfo[] getLocationList([System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)] Location[] objLocation, bool exactMatch, string MapToWebUser) {
        object[] results = this.Invoke("getLocationList", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser});
        return ((LocationGeoInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegingetLocationList(Location[] objLocation, bool exactMatch, string MapToWebUser, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getLocationList", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser}, callback, asyncState);
    }
    
    /// <remarks/>
    public LocationGeoInfo[] EndgetLocationList(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((LocationGeoInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void getLocationListAsync(Location[] objLocation, bool exactMatch, string MapToWebUser) {
        this.getLocationListAsync(objLocation, exactMatch, MapToWebUser, null);
    }
    
    /// <remarks/>
    public void getLocationListAsync(Location[] objLocation, bool exactMatch, string MapToWebUser, object userState) {
        if ((this.getLocationListOperationCompleted == null)) {
            this.getLocationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetLocationListOperationCompleted);
        }
        this.InvokeAsync("getLocationList", new object[] {
                    objLocation,
                    exactMatch,
                    MapToWebUser}, this.getLocationListOperationCompleted, userState);
    }
    
    private void OngetLocationListOperationCompleted(object arg) {
        if ((this.getLocationListCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getLocationListCompleted(this, new getLocationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.GEOvision.dk/MapToWeb/Locations")]
public partial class Location {
    
    private string addressStreetNameField;
    
    private long addressHouseNumberField;
    
    private string addressPostalIDField;
    
    private string addressPlaceNameField;
    
    private string addressPhoneNumberField;
    
    private string areaMunicipalityField;
    
    private string areaCountyField;
    
    private string areaRegionField;
    
    private string areaCountryField;
    
    private long adminStreetIDField;
    
    private long adminMunicipalityIDField;
    
    private long coordinateS34posXField;
    
    private long coordinateS34posYField;
    
    private long coordinateUTMposXField;
    
    private long coordinateUTMposYField;
    
    private double coordinateWGS84posNorthingField;
    
    private double coordinateWGS84posEastingField;
    
    private string mTWlayerItemIDField;
    
    /// <remarks/>
    public string AddressStreetName {
        get {
            return this.addressStreetNameField;
        }
        set {
            this.addressStreetNameField = value;
        }
    }
    
    /// <remarks/>
    public long AddressHouseNumber {
        get {
            return this.addressHouseNumberField;
        }
        set {
            this.addressHouseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string AddressPostalID {
        get {
            return this.addressPostalIDField;
        }
        set {
            this.addressPostalIDField = value;
        }
    }
    
    /// <remarks/>
    public string AddressPlaceName {
        get {
            return this.addressPlaceNameField;
        }
        set {
            this.addressPlaceNameField = value;
        }
    }
    
    /// <remarks/>
    public string AddressPhoneNumber {
        get {
            return this.addressPhoneNumberField;
        }
        set {
            this.addressPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string AreaMunicipality {
        get {
            return this.areaMunicipalityField;
        }
        set {
            this.areaMunicipalityField = value;
        }
    }
    
    /// <remarks/>
    public string AreaCounty {
        get {
            return this.areaCountyField;
        }
        set {
            this.areaCountyField = value;
        }
    }
    
    /// <remarks/>
    public string AreaRegion {
        get {
            return this.areaRegionField;
        }
        set {
            this.areaRegionField = value;
        }
    }
    
    /// <remarks/>
    public string AreaCountry {
        get {
            return this.areaCountryField;
        }
        set {
            this.areaCountryField = value;
        }
    }
    
    /// <remarks/>
    public long AdminStreetID {
        get {
            return this.adminStreetIDField;
        }
        set {
            this.adminStreetIDField = value;
        }
    }
    
    /// <remarks/>
    public long AdminMunicipalityID {
        get {
            return this.adminMunicipalityIDField;
        }
        set {
            this.adminMunicipalityIDField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateS34posX {
        get {
            return this.coordinateS34posXField;
        }
        set {
            this.coordinateS34posXField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateS34posY {
        get {
            return this.coordinateS34posYField;
        }
        set {
            this.coordinateS34posYField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateUTMposX {
        get {
            return this.coordinateUTMposXField;
        }
        set {
            this.coordinateUTMposXField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateUTMposY {
        get {
            return this.coordinateUTMposYField;
        }
        set {
            this.coordinateUTMposYField = value;
        }
    }
    
    /// <remarks/>
    public double CoordinateWGS84posNorthing {
        get {
            return this.coordinateWGS84posNorthingField;
        }
        set {
            this.coordinateWGS84posNorthingField = value;
        }
    }
    
    /// <remarks/>
    public double CoordinateWGS84posEasting {
        get {
            return this.coordinateWGS84posEastingField;
        }
        set {
            this.coordinateWGS84posEastingField = value;
        }
    }
    
    /// <remarks/>
    public string MTWlayerItemID {
        get {
            return this.mTWlayerItemIDField;
        }
        set {
            this.mTWlayerItemIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.GEOvision.dk/MapToWeb/Locations")]
public partial class LocationInfo {
    
    private int locationTypeField;
    
    private string addressStreetNameField;
    
    private long addressHouseNumberField;
    
    private string addressPostalIDField;
    
    private string addressPostalDistrictNameField;
    
    private string addressPlaceNameField;
    
    private long adminStreetIDField;
    
    private long adminMunicipalityIDField;
    
    private string adminCountryIDField;
    
    private string areaMunicipalityNameField;
    
    private string areaCountyNameField;
    
    private string areaRegionNameField;
    
    private string areaCountryNameField;
    
    private LocationGeoInfo objLocationGeoInfoField;
    
    private long infoMessageField;
    
    /// <remarks/>
    public int LocationType {
        get {
            return this.locationTypeField;
        }
        set {
            this.locationTypeField = value;
        }
    }
    
    /// <remarks/>
    public string AddressStreetName {
        get {
            return this.addressStreetNameField;
        }
        set {
            this.addressStreetNameField = value;
        }
    }
    
    /// <remarks/>
    public long AddressHouseNumber {
        get {
            return this.addressHouseNumberField;
        }
        set {
            this.addressHouseNumberField = value;
        }
    }
    
    /// <remarks/>
    public string AddressPostalID {
        get {
            return this.addressPostalIDField;
        }
        set {
            this.addressPostalIDField = value;
        }
    }
    
    /// <remarks/>
    public string AddressPostalDistrictName {
        get {
            return this.addressPostalDistrictNameField;
        }
        set {
            this.addressPostalDistrictNameField = value;
        }
    }
    
    /// <remarks/>
    public string AddressPlaceName {
        get {
            return this.addressPlaceNameField;
        }
        set {
            this.addressPlaceNameField = value;
        }
    }
    
    /// <remarks/>
    public long AdminStreetID {
        get {
            return this.adminStreetIDField;
        }
        set {
            this.adminStreetIDField = value;
        }
    }
    
    /// <remarks/>
    public long AdminMunicipalityID {
        get {
            return this.adminMunicipalityIDField;
        }
        set {
            this.adminMunicipalityIDField = value;
        }
    }
    
    /// <remarks/>
    public string AdminCountryID {
        get {
            return this.adminCountryIDField;
        }
        set {
            this.adminCountryIDField = value;
        }
    }
    
    /// <remarks/>
    public string AreaMunicipalityName {
        get {
            return this.areaMunicipalityNameField;
        }
        set {
            this.areaMunicipalityNameField = value;
        }
    }
    
    /// <remarks/>
    public string AreaCountyName {
        get {
            return this.areaCountyNameField;
        }
        set {
            this.areaCountyNameField = value;
        }
    }
    
    /// <remarks/>
    public string AreaRegionName {
        get {
            return this.areaRegionNameField;
        }
        set {
            this.areaRegionNameField = value;
        }
    }
    
    /// <remarks/>
    public string AreaCountryName {
        get {
            return this.areaCountryNameField;
        }
        set {
            this.areaCountryNameField = value;
        }
    }
    
    /// <remarks/>
    public LocationGeoInfo objLocationGeoInfo {
        get {
            return this.objLocationGeoInfoField;
        }
        set {
            this.objLocationGeoInfoField = value;
        }
    }
    
    /// <remarks/>
    public long InfoMessage {
        get {
            return this.infoMessageField;
        }
        set {
            this.infoMessageField = value;
        }
    }
}

/// <summary>
/// PPP ADDED!!
/// </summary>
public class LocationGeoInfoConverter : ExpandableObjectConverter
{
    public override object ConvertTo(ITypeDescriptorContext context,
        CultureInfo culture,
        object value,
        System.Type destinationType)
    {
        if (destinationType == typeof(System.String) && (value is LocationGeoInfo))
        {
            LocationGeoInfo so = (LocationGeoInfo)value;
            return so.AdminCountry + " : " + so.CoordinateX + " " + so.CoordinateY + " : " + so.InfoMessage;
        }
        return base.ConvertTo(context, culture, value, destinationType);
    }
}
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.GEOvision.dk/MapToWeb/Locations")]
[TypeConverterAttribute(typeof(LocationGeoInfoConverter))]
public partial class LocationGeoInfo
{
    
    private int locationTypeField;
    
    private long coordinateRouteXField;
    
    private long coordinateRouteYField;
    
    private long coordinateXField;
    
    private long coordinateYField;
    
    private long extentXmaxField;
    
    private long extentXminField;
    
    private long extentYmaxField;
    
    private long extentYminField;
    
    private long locationIDField;
    
    private string adminCountryField;
    
    private long infoMessageField;
    
    /// <remarks/>
    public int LocationType {
        get {
            return this.locationTypeField;
        }
        set {
            this.locationTypeField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateRouteX {
        get {
            return this.coordinateRouteXField;
        }
        set {
            this.coordinateRouteXField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateRouteY {
        get {
            return this.coordinateRouteYField;
        }
        set {
            this.coordinateRouteYField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateX {
        get {
            return this.coordinateXField;
        }
        set {
            this.coordinateXField = value;
        }
    }
    
    /// <remarks/>
    public long CoordinateY {
        get {
            return this.coordinateYField;
        }
        set {
            this.coordinateYField = value;
        }
    }
    
    /// <remarks/>
    public long ExtentXmax {
        get {
            return this.extentXmaxField;
        }
        set {
            this.extentXmaxField = value;
        }
    }
    
    /// <remarks/>
    public long ExtentXmin {
        get {
            return this.extentXminField;
        }
        set {
            this.extentXminField = value;
        }
    }
    
    /// <remarks/>
    public long ExtentYmax {
        get {
            return this.extentYmaxField;
        }
        set {
            this.extentYmaxField = value;
        }
    }
    
    /// <remarks/>
    public long ExtentYmin {
        get {
            return this.extentYminField;
        }
        set {
            this.extentYminField = value;
        }
    }
    
    /// <remarks/>
    public long LocationID {
        get {
            return this.locationIDField;
        }
        set {
            this.locationIDField = value;
        }
    }
    
    /// <remarks/>
    public string AdminCountry {
        get {
            return this.adminCountryField;
        }
        set {
            this.adminCountryField = value;
        }
    }
    
    /// <remarks/>
    public long InfoMessage {
        get {
            return this.infoMessageField;
        }
        set {
            this.infoMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void getLocationCompletedEventHandler(object sender, getLocationCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public LocationGeoInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((LocationGeoInfo)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void getLocationWithInfoCompletedEventHandler(object sender, getLocationWithInfoCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLocationWithInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLocationWithInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public LocationInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((LocationInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void getLocationListCompletedEventHandler(object sender, getLocationListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getLocationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getLocationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public LocationGeoInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((LocationGeoInfo[])(this.results[0]));
        }
    }
}
