//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.21006.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="locationRoutingSoap", Namespace="http://tempuri.org/")]
public partial class locationRouting : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback LocationSearchOperationCompleted;
    
    /// <remarks/>
    public locationRouting() {
        this.Url = "http://hle.htzpartners.com/locationSearch/locationRouting.asmx";
    }
    
    /// <remarks/>
    public event LocationSearchCompletedEventHandler LocationSearchCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LocationSearch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public LocationList LocationSearch(string ZipCode, string AreaCode, string Prefix) {
        object[] results = this.Invoke("LocationSearch", new object[] {
                    ZipCode,
                    AreaCode,
                    Prefix});
        return ((LocationList)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginLocationSearch(string ZipCode, string AreaCode, string Prefix, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("LocationSearch", new object[] {
                    ZipCode,
                    AreaCode,
                    Prefix}, callback, asyncState);
    }
    
    /// <remarks/>
    public LocationList EndLocationSearch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((LocationList)(results[0]));
    }
    
    /// <remarks/>
    public void LocationSearchAsync(string ZipCode, string AreaCode, string Prefix) {
        this.LocationSearchAsync(ZipCode, AreaCode, Prefix, null);
    }
    
    /// <remarks/>
    public void LocationSearchAsync(string ZipCode, string AreaCode, string Prefix, object userState) {
        if ((this.LocationSearchOperationCompleted == null)) {
            this.LocationSearchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLocationSearchOperationCompleted);
        }
        this.InvokeAsync("LocationSearch", new object[] {
                    ZipCode,
                    AreaCode,
                    Prefix}, this.LocationSearchOperationCompleted, userState);
    }
    
    private void OnLocationSearchOperationCompleted(object arg) {
        if ((this.LocationSearchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.LocationSearchCompleted(this, new LocationSearchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class LocationList {
    
    private ErrorResponse errorResponseField;
    
    private Location[] rentalLocationsField;
    
    private int numberOfLocationsReturnedField;
    
    /// <remarks/>
    public ErrorResponse ErrorResponse {
        get {
            return this.errorResponseField;
        }
        set {
            this.errorResponseField = value;
        }
    }
    
    /// <remarks/>
    public Location[] RentalLocations {
        get {
            return this.rentalLocationsField;
        }
        set {
            this.rentalLocationsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NumberOfLocationsReturned {
        get {
            return this.numberOfLocationsReturnedField;
        }
        set {
            this.numberOfLocationsReturnedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class ErrorResponse {
    
    private int codeField;
    
    private string messageField;
    
    /// <remarks/>
    public int Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class Location {
    
    private string locationOAGField;
    
    private int rankField;
    
    private string addressStreet1Field;
    
    private string addressStreet2Field;
    
    private string addressCityField;
    
    private string addressStateField;
    
    private string addressZipCodeField;
    
    private string phoneNumberField;
    
    /// <remarks/>
    public string LocationOAG {
        get {
            return this.locationOAGField;
        }
        set {
            this.locationOAGField = value;
        }
    }
    
    /// <remarks/>
    public int Rank {
        get {
            return this.rankField;
        }
        set {
            this.rankField = value;
        }
    }
    
    /// <remarks/>
    public string AddressStreet1 {
        get {
            return this.addressStreet1Field;
        }
        set {
            this.addressStreet1Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressStreet2 {
        get {
            return this.addressStreet2Field;
        }
        set {
            this.addressStreet2Field = value;
        }
    }
    
    /// <remarks/>
    public string AddressCity {
        get {
            return this.addressCityField;
        }
        set {
            this.addressCityField = value;
        }
    }
    
    /// <remarks/>
    public string AddressState {
        get {
            return this.addressStateField;
        }
        set {
            this.addressStateField = value;
        }
    }
    
    /// <remarks/>
    public string AddressZipCode {
        get {
            return this.addressZipCodeField;
        }
        set {
            this.addressZipCodeField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void LocationSearchCompletedEventHandler(object sender, LocationSearchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class LocationSearchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal LocationSearchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public LocationList Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((LocationList)(this.results[0]));
        }
    }
}
