//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.21006.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="MovieInformationSoap", Namespace="http://intraworks.net/")]
public partial class MovieInformation : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback GetByUPCOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetByIDOperationCompleted;
    
    /// <remarks/>
    public MovieInformation() {
        this.Url = "http://www.intraworks.net/DVDDatabase/MovieInformation.asmx";
    }
    
    /// <remarks/>
    public event GetByUPCCompletedEventHandler GetByUPCCompleted;
    
    /// <remarks/>
    public event GetByIDCompletedEventHandler GetByIDCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intraworks.net/GetByUPC", RequestNamespace="http://intraworks.net/", ResponseNamespace="http://intraworks.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Movie GetByUPC(string upc) {
        object[] results = this.Invoke("GetByUPC", new object[] {
                    upc});
        return ((Movie)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetByUPC(string upc, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetByUPC", new object[] {
                    upc}, callback, asyncState);
    }
    
    /// <remarks/>
    public Movie EndGetByUPC(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Movie)(results[0]));
    }
    
    /// <remarks/>
    public void GetByUPCAsync(string upc) {
        this.GetByUPCAsync(upc, null);
    }
    
    /// <remarks/>
    public void GetByUPCAsync(string upc, object userState) {
        if ((this.GetByUPCOperationCompleted == null)) {
            this.GetByUPCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByUPCOperationCompleted);
        }
        this.InvokeAsync("GetByUPC", new object[] {
                    upc}, this.GetByUPCOperationCompleted, userState);
    }
    
    private void OnGetByUPCOperationCompleted(object arg) {
        if ((this.GetByUPCCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetByUPCCompleted(this, new GetByUPCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://intraworks.net/GetByID", RequestNamespace="http://intraworks.net/", ResponseNamespace="http://intraworks.net/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public Movie GetByID(int ID) {
        object[] results = this.Invoke("GetByID", new object[] {
                    ID});
        return ((Movie)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetByID(int ID, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetByID", new object[] {
                    ID}, callback, asyncState);
    }
    
    /// <remarks/>
    public Movie EndGetByID(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Movie)(results[0]));
    }
    
    /// <remarks/>
    public void GetByIDAsync(int ID) {
        this.GetByIDAsync(ID, null);
    }
    
    /// <remarks/>
    public void GetByIDAsync(int ID, object userState) {
        if ((this.GetByIDOperationCompleted == null)) {
            this.GetByIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetByIDOperationCompleted);
        }
        this.InvokeAsync("GetByID", new object[] {
                    ID}, this.GetByIDOperationCompleted, userState);
    }
    
    private void OnGetByIDOperationCompleted(object arg) {
        if ((this.GetByIDCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetByIDCompleted(this, new GetByIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://intraworks.net/")]
public partial class Movie {
    
    private int idField;
    
    private string titleField;
    
    private string sortTitleField;
    
    private string overviewField;
    
    private string ratingField;
    
    private string genreField;
    
    private int runningTimeField;
    
    private int releaseYearField;
    
    private string imageUrlField;
    
    /// <remarks/>
    public int ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string SortTitle {
        get {
            return this.sortTitleField;
        }
        set {
            this.sortTitleField = value;
        }
    }
    
    /// <remarks/>
    public string Overview {
        get {
            return this.overviewField;
        }
        set {
            this.overviewField = value;
        }
    }
    
    /// <remarks/>
    public string Rating {
        get {
            return this.ratingField;
        }
        set {
            this.ratingField = value;
        }
    }
    
    /// <remarks/>
    public string Genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <remarks/>
    public int RunningTime {
        get {
            return this.runningTimeField;
        }
        set {
            this.runningTimeField = value;
        }
    }
    
    /// <remarks/>
    public int ReleaseYear {
        get {
            return this.releaseYearField;
        }
        set {
            this.releaseYearField = value;
        }
    }
    
    /// <remarks/>
    public string ImageUrl {
        get {
            return this.imageUrlField;
        }
        set {
            this.imageUrlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void GetByUPCCompletedEventHandler(object sender, GetByUPCCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetByUPCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetByUPCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Movie Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Movie)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void GetByIDCompletedEventHandler(object sender, GetByIDCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetByIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal GetByIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Movie Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Movie)(this.results[0]));
        }
    }
}
