//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using System.Globalization;

// 
// This source code was auto-generated by wsdl, Version=4.0.21006.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="NEDSoap", Namespace="http://skyservice.pha.jhu.edu")]
public partial class NED : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ObjByNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObjNearNameOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObjNearPosnOperationCompleted;
    
    private System.Threading.SendOrPostCallback CvsRevisionsOperationCompleted;
    
    /// <remarks/>
    public NED() {
        this.Url = "http://voservices.net/NED/ws_v1_0/NED.asmx";
    }
    
    /// <remarks/>
    public event ObjByNameCompletedEventHandler ObjByNameCompleted;
    
    /// <remarks/>
    public event ObjNearNameCompletedEventHandler ObjNearNameCompleted;
    
    /// <remarks/>
    public event ObjNearPosnCompletedEventHandler ObjNearPosnCompleted;
    
    /// <remarks/>
    public event CvsRevisionsCompletedEventHandler CvsRevisionsCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://skyservice.pha.jhu.edu/ObjByName", RequestNamespace="http://skyservice.pha.jhu.edu", ResponseNamespace="http://skyservice.pha.jhu.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ObjInfo ObjByName(string objname) {
        object[] results = this.Invoke("ObjByName", new object[] {
                    objname});
        return ((ObjInfo)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObjByName(string objname, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObjByName", new object[] {
                    objname}, callback, asyncState);
    }
    
    /// <remarks/>
    public ObjInfo EndObjByName(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ObjInfo)(results[0]));
    }
    
    /// <remarks/>
    public void ObjByNameAsync(string objname) {
        this.ObjByNameAsync(objname, null);
    }
    
    /// <remarks/>
    public void ObjByNameAsync(string objname, object userState) {
        if ((this.ObjByNameOperationCompleted == null)) {
            this.ObjByNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObjByNameOperationCompleted);
        }
        this.InvokeAsync("ObjByName", new object[] {
                    objname}, this.ObjByNameOperationCompleted, userState);
    }
    
    private void OnObjByNameOperationCompleted(object arg) {
        if ((this.ObjByNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObjByNameCompleted(this, new ObjByNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://skyservice.pha.jhu.edu/ObjNearName", RequestNamespace="http://skyservice.pha.jhu.edu", ResponseNamespace="http://skyservice.pha.jhu.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ObjInfo[] ObjNearName(string objname, double radius) {
        object[] results = this.Invoke("ObjNearName", new object[] {
                    objname,
                    radius});
        return ((ObjInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObjNearName(string objname, double radius, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObjNearName", new object[] {
                    objname,
                    radius}, callback, asyncState);
    }
    
    /// <remarks/>
    public ObjInfo[] EndObjNearName(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ObjInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void ObjNearNameAsync(string objname, double radius) {
        this.ObjNearNameAsync(objname, radius, null);
    }
    
    /// <remarks/>
    public void ObjNearNameAsync(string objname, double radius, object userState) {
        if ((this.ObjNearNameOperationCompleted == null)) {
            this.ObjNearNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObjNearNameOperationCompleted);
        }
        this.InvokeAsync("ObjNearName", new object[] {
                    objname,
                    radius}, this.ObjNearNameOperationCompleted, userState);
    }
    
    private void OnObjNearNameOperationCompleted(object arg) {
        if ((this.ObjNearNameCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObjNearNameCompleted(this, new ObjNearNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://skyservice.pha.jhu.edu/ObjNearPosn", RequestNamespace="http://skyservice.pha.jhu.edu", ResponseNamespace="http://skyservice.pha.jhu.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public ObjInfo[] ObjNearPosn(double ra, double dec, double radius) {
        object[] results = this.Invoke("ObjNearPosn", new object[] {
                    ra,
                    dec,
                    radius});
        return ((ObjInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObjNearPosn(double ra, double dec, double radius, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObjNearPosn", new object[] {
                    ra,
                    dec,
                    radius}, callback, asyncState);
    }
    
    /// <remarks/>
    public ObjInfo[] EndObjNearPosn(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ObjInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void ObjNearPosnAsync(double ra, double dec, double radius) {
        this.ObjNearPosnAsync(ra, dec, radius, null);
    }
    
    /// <remarks/>
    public void ObjNearPosnAsync(double ra, double dec, double radius, object userState) {
        if ((this.ObjNearPosnOperationCompleted == null)) {
            this.ObjNearPosnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObjNearPosnOperationCompleted);
        }
        this.InvokeAsync("ObjNearPosn", new object[] {
                    ra,
                    dec,
                    radius}, this.ObjNearPosnOperationCompleted, userState);
    }
    
    private void OnObjNearPosnOperationCompleted(object arg) {
        if ((this.ObjNearPosnCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObjNearPosnCompleted(this, new ObjNearPosnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://skyservice.pha.jhu.edu/Revisions", RequestElementName="Revisions", RequestNamespace="http://skyservice.pha.jhu.edu", ResponseElementName="RevisionsResponse", ResponseNamespace="http://skyservice.pha.jhu.edu", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlArrayAttribute("RevisionsResult")]
    public string[] CvsRevisions() {
        object[] results = this.Invoke("CvsRevisions", new object[0]);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginCvsRevisions(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("CvsRevisions", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndCvsRevisions(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void CvsRevisionsAsync() {
        this.CvsRevisionsAsync(null);
    }
    
    /// <remarks/>
    public void CvsRevisionsAsync(object userState) {
        if ((this.CvsRevisionsOperationCompleted == null)) {
            this.CvsRevisionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCvsRevisionsOperationCompleted);
        }
        this.InvokeAsync("CvsRevisions", new object[0], this.CvsRevisionsOperationCompleted, userState);
    }
    
    private void OnCvsRevisionsOperationCompleted(object arg) {
        if ((this.CvsRevisionsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.CvsRevisionsCompleted(this, new CvsRevisionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skyservice.pha.jhu.edu")]
public partial class ObjInfo {
    
    private CrossID[] arrayOfCrossIDField;
    
    private double distField;
    
    private int no_refField;
    
    private int no_noteField;
    
    private int no_photomField;
    
    private string objtypeField;
    
    private double raField;
    
    private double decField;
    
    private double unc_majField;
    
    private double unc_minField;
    
    private double unc_angField;
    
    private string refcodeField;
    
    private MoreData[] arrayOfMoreDataField;
    
    /// <remarks/>
    public CrossID[] ArrayOfCrossID {
        get {
            return this.arrayOfCrossIDField;
        }
        set {
            this.arrayOfCrossIDField = value;
        }
    }
    
    /// <remarks/>
    public double dist {
        get {
            return this.distField;
        }
        set {
            this.distField = value;
        }
    }
    
    /// <remarks/>
    public int no_ref {
        get {
            return this.no_refField;
        }
        set {
            this.no_refField = value;
        }
    }
    
    /// <remarks/>
    public int no_note {
        get {
            return this.no_noteField;
        }
        set {
            this.no_noteField = value;
        }
    }
    
    /// <remarks/>
    public int no_photom {
        get {
            return this.no_photomField;
        }
        set {
            this.no_photomField = value;
        }
    }
    
    /// <remarks/>
    public string objtype {
        get {
            return this.objtypeField;
        }
        set {
            this.objtypeField = value;
        }
    }
    
    /// <remarks/>
    public double ra {
        get {
            return this.raField;
        }
        set {
            this.raField = value;
        }
    }
    
    /// <remarks/>
    public double dec {
        get {
            return this.decField;
        }
        set {
            this.decField = value;
        }
    }
    
    /// <remarks/>
    public double unc_maj {
        get {
            return this.unc_majField;
        }
        set {
            this.unc_majField = value;
        }
    }
    
    /// <remarks/>
    public double unc_min {
        get {
            return this.unc_minField;
        }
        set {
            this.unc_minField = value;
        }
    }
    
    /// <remarks/>
    public double unc_ang {
        get {
            return this.unc_angField;
        }
        set {
            this.unc_angField = value;
        }
    }
    
    /// <remarks/>
    public string refcode {
        get {
            return this.refcodeField;
        }
        set {
            this.refcodeField = value;
        }
    }
    
    /// <remarks/>
    public MoreData[] ArrayOfMoreData {
        get {
            return this.arrayOfMoreDataField;
        }
        set {
            this.arrayOfMoreDataField = value;
        }
    }
}

/// <summary>
/// PPP ADDED!!
/// </summary>
public class CrossIDConverter : ExpandableObjectConverter 
{
    public override object ConvertTo(ITypeDescriptorContext context,
        CultureInfo culture,
        object value,
        System.Type destinationType)
    {
        if ( destinationType == typeof(System.String) && (value is CrossID) )
        {
            CrossID so = (CrossID)value;
            return so.objtype + " : " + so.objname;
        }
        return base.ConvertTo(context, culture, value, destinationType);
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skyservice.pha.jhu.edu")]
[TypeConverterAttribute(typeof(CrossIDConverter))]
public partial class CrossID {
    
    private string objnameField;
    
    private string objtypeField;
    
    /// <remarks/>
    public string objname {
        get {
            return this.objnameField;
        }
        set {
            this.objnameField = value;
        }
    }
    
    /// <remarks/>
    public string objtype {
        get {
            return this.objtypeField;
        }
        set {
            this.objtypeField = value;
        }
    }
}

/// <summary>
/// PPP ADDED!!
/// </summary>
public class MoreDataConverter : ExpandableObjectConverter
{
    public override object ConvertTo(ITypeDescriptorContext context,
        CultureInfo culture,
        object value,
        System.Type destinationType)
    {
        if (destinationType == typeof(System.String) && (value is MoreData))
        {
            MoreData so = (MoreData)value;
            return so.data_typec + " : " + so.data;
        }
        return base.ConvertTo(context, culture, value, destinationType);
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://skyservice.pha.jhu.edu")]
[TypeConverterAttribute(typeof(MoreDataConverter))]
public partial class MoreData
{
    
    private string data_typecField;
    
    private string dataField;
    
    /// <remarks/>
    public string data_typec {
        get {
            return this.data_typecField;
        }
        set {
            this.data_typecField = value;
        }
    }
    
    /// <remarks/>
    public string data {
        get {
            return this.dataField;
        }
        set {
            this.dataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void ObjByNameCompletedEventHandler(object sender, ObjByNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObjByNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObjByNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ObjInfo Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ObjInfo)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void ObjNearNameCompletedEventHandler(object sender, ObjNearNameCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObjNearNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObjNearNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ObjInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ObjInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void ObjNearPosnCompletedEventHandler(object sender, ObjNearPosnCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObjNearPosnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObjNearPosnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ObjInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ObjInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
public delegate void CvsRevisionsCompletedEventHandler(object sender, CvsRevisionsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.21006.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class CvsRevisionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal CvsRevisionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}
